const staticResponses = {
	registerPlatformDevice: {},
	registerUsertoDevice: {},

	// Auth API
	fetchCountryConfiguration: {
		about_us:
			'<p>&nbsp;</p><blockquote><img style="display: block; margin-left: auto; margin-right: auto;" src="https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/App_Icon_xecPs8V.png" alt="" width="200" height="200" /></blockquote><p>&nbsp;</p><p><span data-preserver-spaces="true">Nesto Hypermarkets bring you one-step closer to our shelves through this Customer Care program that is intended to suit the mood and purchase patterns of each one of you.</span></p><p>&nbsp;</p><p><span data-preserver-spaces="true">INAAM is a loyalty Program specially designed to aid the Purchasing habits of our loyal customers extending our service to a family audience by giving them an opportunity to shop more at much less through this innovative program.</span></p><p>&nbsp;</p><p><span data-preserver-spaces="true">Would earn substantial savings to the vast number of customers who consider NESTO as their second home. Currently operating in the countries of UAE, KSA, Bahrain, Oman, Qatar, Kuwait and India the NESTO footprint is soon expected to expand into other markets in Asia.</span></p><p>&nbsp;</p><p><span data-preserver-spaces="true">NESTO is all about getting you All the Quality you need, All the Freshness you need, All the Style you need, All the Fashion you need, All the Range you need and in short. All that you need to maintain a cost effective, yet quality driven lifestyle.</span></p><p>&nbsp;</p><p><span data-preserver-spaces="true">INAAM Adds value to this relationship by fetching you Reward Points for every purchase enabling you to redeem these points for more purchases.</span></p><p><span data-preserver-spaces="true">&nbsp;</span></p><h3>How to collect points</h3><p><span style="font-weight: 400;">It is simple, just produce your Digital card or tell registered mobile number at the time of your purchase, the cashier will scan your card and complete the billing. The points will be credited to your card within 24 hours. Please note that the points cannot be collected for Cigarettes and Telephone cards.</span></p><p>&nbsp;</p><h3>How many points do you collect for your purchase?&nbsp;</h3><p><span style="font-weight: 400;">You will get 1 point for every Rs. 100 purchase.</span></p><p>&nbsp;</p><h3>What do you get for the points you collected?</h3><div><img style="display: block; margin-left: auto; margin-right: auto;" src="https://inaam-app.s3.eu-central-1.amazonaws.com/original_image/Screenshot_2022-02-14_at_11.24.46_PM.png" alt="" width="350" height="236" /></div><p>&nbsp;</p><h3>How and when to get your vouchers (Redemption of points)?</h3><ul><li><span data-preserver-spaces="true">You can redeem your points to get the voucher on the basis of above qualification criteria.</span></li><li><span data-preserver-spaces="true">Redemption of points for voucher is possible at any time from the Inaam kiosk or the customer service Desk.</span></li><li><span data-preserver-spaces="true">Once you redeem your points for vouchers equivalent points will be deducted from your total points available as on that date.</span></li></ul>',
		contact_info: {
			address:
				'Nesto Management Office, 2/1149G, HiLITE Mall, HiLITE City, NH Thondayad Bypass, Kozhikode, Kerala- 673014',
			email: 'inaamsrvc@nestogroup.com',
			mail: 'inaamsrvc@nestogroup.com',
			phone_number: '+91 9746 311 522',
		},
		contact_number_length: 10,
		country_code: '91',
		currency: 'INR',
		currency_equivalent_in_points: 2,
		date_created: '2022-02-14T06:09:18.571456+05:30',
		date_modified: '2022-09-22T10:12:30.001601+05:30',
		decimal_points: 2,
		faq: [
			{
				answer: "<p>Inaam is Nesto Hypermarket L.L.C's rewards programme. If you shop often at our outlets across the U.A.E, this programme clusters points which can be redeemed for shopping vouchers. By registering for the Inaam, you get: Free membership for life. Earn monetary reward vouchers. Exclusive offers, including special invitations to in-store activities and sales motions.</p>",
				question: 'What is Inaam?',
			},
		],
		is_active: true,
		maximum_sharing_amount: 1000,
		minimum_sharing_amount: 500,
		minimum_voucher_amount: 100,
		privacy_policy:
			'<p><span data-preserver-spaces="true">Nesto INAAM Programme is a loyalty programme operated by Nesto Hypermarket L.L.C, its subsidiaries, associates and the branches under its management control (hereinafter referred to as &lsquo;Nesto Group&rsquo; or &lsquo;Nesto&rsquo; ). As a member, you will earn Points when making qualifying purchases at all Nesto stores when showing your INAAM Membership Card at the time of purchase. These terms and conditions relate to the membership, earning and redeeming of points under the Programme from its launch.</span></p><p><span data-preserver-spaces="true">&nbsp;</span></p><h3>General</h3><ol><li><span data-preserver-spaces="true">Nesto reserves the right to withdraw or cancel any or all of the Membership Cards issued; refuse to award Points; withdraw Points; refuse the right to redeem Points collected for any breach of these conditions or failure to pay for the purchases without prior notice.</span></li><li><span data-preserver-spaces="true">By using your INAAM Membership Card in any of the Programme&rsquo;s participating outlets or with the partners for the purpose of earning Points or availaing discounts, you automatically provide acceptance of the Programme along with its rules, terms and conditions, which are subject to amendment from time to time.</span></li><li><span data-preserver-spaces="true">Your membership of the Programme can be revoked or refused if you are involved in any act of fraud, shoplifting, re-selling or bulk buying, cheating with or without cause and without The membership can also be revoked if you are found to be involved in any sort of misuse of the INAAM Membership Card of the programme. In this given scenario all your existing points on the INAAM Membership Card shall also stand cancelled and cannot be redeemed.</span></li><li><span data-preserver-spaces="true">Nesto reserves the right to modify or close the Programme, or to change, cancel or withdraw any of the terms and conditions, without assigning any reason whatsoever at any point of time at its own discretion. It reserves the right to discontinue programme memberships - existing or new - temporarily or permanently for a period of time, as decided by the management.</span></li><li><span data-preserver-spaces="true">Benefits and offers made to you through the programme may change or be withdrawn without prior Nesto will not be responsible for any liability arising from such situations.</span></li><li><span data-preserver-spaces="true">No points will be issued on any products that are sold on offer or at a discounted However it is the discretion of Nesto management to award points on the discounted products at any ratio that it may deemed fit.</span></li><li><span data-preserver-spaces="true">Nesto has the right to modify the manner in which Points are earned and redeemed, including the number of Points earned and the value of these points, without prior notice.</span></li><li><span data-preserver-spaces="true">You are responsible for notifying the customer service desk (CSD), for any changes in your address or contact details.</span></li><li><span data-preserver-spaces="true">Nesto has the right to contact members for the purpose of providing membership information, account statements and redemption vouchers even if you have opted out of receiving communications.</span></li>   <li><span data-preserver-spaces="true">Nesto will not be liable for any unlawful or misuse of an INAAM Membership Card or account at the kiosk. Card holder will have to ensure that the card is pulled out of the kiosk and logged out before leaving the kiosk.</span></li><li><span data-preserver-spaces="true">As a member you are responsible for any loss, damage or theft of your Membership Card or Rewards You must report any loss, damage or theft immediately to the Customer Service Desk of the nearest store. Replacement of INAAM Membership Cards that are issued for any reason whatsoever will be replaced for a penalty of AED 5/-, which will be collected at the store. In case of loss of the INAAM card (Master Card), a new membership card will be issued to you with a new membership to avoid fraudulent use of the previous card. The replacement / new card will be ready for collection at the store of your choice within 10 working days. Meanwhile you may use your supplementary / mastercard or virtual card for the purpose of earning points. In case the card has to be blocked then, again the card holder will have to notify at the CSD of our hypermarkets.</span></li><li><span data-preserver-spaces="true">By participating in the programme, you consent to Nesto can retain the information provided to Nesto about you, including details of any purchases made and the use of this information to offer you products and services that are likely to be of interest and for Nesto market research purposes.</span></li><li><span data-preserver-spaces="true">Member may cancel his / her card by a written application submitted at the CSD of any of the Once the application is approved, the member shall be allowed to redeem his balance points provided it falls within the minimum redemption threshold of 500 points. Any points that are ineligible for redemption shall be cancelled.</span></li><li><span data-preserver-spaces="true">Rewards Programme is inseparably associated with Internet availability. As such, the Customer Loyalty Program is susceptible to down time whenever the Internet is NESTO accepts no responsibility for Internet communication challenges that negatively impact its Customer Loyalty Program. NESTO will make every effort to ensure that customers receive points earned on purchases transacted during times when the Internet is unavailable. However, there can be no redemption of points during times when the Internet is unavailable.</span></li><li><span data-preserver-spaces="true">These terms and conditions shall be governed by the laws of the country issuing the card and any dispute may be referred to the courts of the respective country.</span></li><li><span data-preserver-spaces="true">The terms and conditions as published on the Website Inaamrewards.com as updated from time to time shall be final and binding and supersede the terms and conditions herein and other information as provided in relation to the Programme.</span></li></ol><p>&nbsp;</p><h3>Membership</h3><ol><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">The INAAM </span><span style="font-weight: 400;">Membership Card shall always remain the property of the Nesto and you will only be the custodian of the same.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Only an individual who has attained the age of 18 years is entitled for the membership of the Program. Applications received from members under the age of 18 will be blocked for redemption of points till the member attains the age of 18.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">The membership to the Program is free and the membership card is not a corporate card/corporate membership and is not valid for Nesto staff.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">The INAAM</span><span style="font-weight: 400;">&nbsp;Membership card can only be used at stores and other promotional third party partners who may from time to time be part of the program. These third party offerings will be subject to the terms and conditions of the third party involved</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Membership is non-transferable and can only be used by you, as the authorized Cardholder. The Membership will be allotted purely at the discretion of the management and final decisions on all matters relating to the INAAM </span><span style="font-weight: 400;">Membership Card shall rest with Nesto.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">A member who has not transacted within a 6 month period will be deemed by the Program as &lsquo;Inactive&rsquo;. No communications will be sent to members in Inactive Status. To avoid becoming an Inactive member, ensure that you have at least one transaction within a 6 month period. Members in Inactive Status will be re-activated to Active Status as soon as they make their next transaction.</span></li>    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">A member shall at all times hold only one valid INAAM </span><span style="font-weight: 400;">membership card in his name and mobile number. If found otherwise, Nesto reserves the right to cancel all INAAM M</span><span style="font-weight: 400;"><span style="font-weight: 400;">embership Cards held by the Person in his name and the points accrued in such cards cannot be redeemed. Once an existing member applies for a new INAAM Membership Card his existing temporary account will be merged with the new&nbsp; account within 7 days of registration. On issuing the new INAAM Membership Card, the INAAM Old Membership Card stands cancelled and points can be earned only in the new membership card</span></span></li></ol><p>&nbsp;</p><h3>Earning</h3><ol><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Points can only be earned when the INAAM </span><span style="font-weight: 400;">Digital Membership Card or registered m</span>obile number is produced at the time of making the purchase at all participating Nesto Hypermarket outlets in India only. No retrospective claims for the transactions made in the past will be entertained.</li><li style="font-weight: 400;" aria-level="1">All Points earned under the Nesto program are valid till further notice. All unused Points over 24 months will expire and shall not be available for redemption. You can access your account details at any time on&nbsp; INAAM App.</li><li style="font-weight: 400;" aria-level="1">Points once redeemed against a purchase can in no event be re-credited.</li><li style="font-weight: 400;" aria-level="1">All purchase returns must happen as per Nesto terms of purchase. In the event of a Purchase Return by a member, all points earned on the original transaction for the returned items will be reversed from the members account, including any bonus points earned on promotional items.</li><li style="font-weight: 400;" aria-level="1">Your Points balance cannot be pooled with the Points balance of any other member at any point of time.</li><li style="font-weight: 400;" aria-level="1">Points earning is as per the prescribed earning rate outlined in the point structure system as shown on the INAAM Application. Nesto reserves the right to change all or some of the earning rates without prior notification. However, Nesto will endeavor to advise you of any changes in the earning rates in advance.</li><li style="font-weight: 400;" aria-level="1">Points can be earned only at participating outlets as set forth in the membership guide and on the program website. Nesto reserves the right to add or remove any of the outlets at any time without prior notification. Nesto&nbsp; will endeavor to advise you of any changes to outlets in advance.</li><li style="font-weight: 400;" aria-level="1">Points earned will be available for redemption only after 24 hours from the transaction date.</li><li style="font-weight: 400;" aria-level="1">Points cannot be earned in conjunction with any other programs and co-marketing partnerships.</li><li style="font-weight: 400;" aria-level="1">Points cannot be earned on Cigarette, Tobacco and Telephone cards.</li></ol><p>&nbsp;</p><h3>Redemption</h3><ol><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">INAAM Rewards Vouchers will be issued to all members who have reached the threshold of 100 points subject to Nesto Hypermarket having the complete updated profile of the Member. INAAM </span><span style="font-weight: 400;">Rewards Voucher will be issued in multiples of Rs. 50. Any balance remaining in your account will be used towards the next Rewards Voucher.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">INAAM Rewards Vouchers are valid as per the validity period indicated on the voucher and is only for a one time usage. Non-usage of the INAAM </span><span style="font-weight: 400;">Rewards voucher within the specified time limit will result in expiry of the Rewards Voucher and the points.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">&nbsp;Digital Rewards Vouchers are non-refundable.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Members will be required to sign the INAAM </span><span style="font-weight: 400;">Rewards Voucher at the time of redemption.</span></li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">INAAM Membership Card can be used only in the country of issuance. INAAM </span>Rewards Vouchers can also be redeemed only in the country of issuance.</li>        <li style="font-weight: 400;" aria-level="1">INAAM Rewards Vouchers cannot be exchanged for cash, and no amount can be returned in cash for purchases made through INAAM Rewards Vouchers.</li><li style="font-weight: 400;" aria-level="1">If the value of the purchase is more than the value of the INAAM Rewards Voucher, the balance amount must be paid by the member using a valid payment method.</li><li style="font-weight: 400;" aria-level="1">INAAM Rewards vouchers cannot be purchased using cash or any other form of payment.</li><li style="font-weight: 400;" aria-level="1">INAAM Rewards Vouchers are valid for 15 days from the date of issue specified on the voucher. Non-usage of the digital voucher within the specified time limit will result in expiry of the voucher.</li><li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">INAAM Points would expire in 24 months from the date they are earned. Should a member&rsquo;s points are expired on his or her account, the Points in that account will be cancelled. As set forth in these Program Rules, Nesto has the right to cancel all or some of the Points in a Member&rsquo;s account should Nesto determine, in its sole discretion, that the Member has misrepresented the program.</span></li></ol>',
		region_short_name: 'IN',
		sms_vendor: 'vh',
		status: 200,
		timezone: 'Asia/Kolkata',
		uuid: '85fc0e78-fe66-4850-966d-92aef3c99edb',
		voucher_access_time: 0,
		voucher_point_decimal: 0,
	},
	sendLoginOTP: { status: 200 },
	customerLogin: {
		has_multiple_cards: false,
		is_new_user: false,
		is_profile_complete: true,
		referral_code: null,
		status: 200,
		token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjkxODg4ODg4ODg4OCIsImV4cCI6MTY4MTc0MTQzOX0.mqpsr8A2Y90haV4lisoS_7SzgbuiAL1vwXnumsROFaU',
		uuid: '8d98be09-abe4-467c-bb03-f9f29db0ce27',
		verified: true,
	},
	fetchUserProfile: {
		card_number: '9100005571',
		contact_number: '8888888888',
		country_code: '91',
		date_created: '02-25-2022',
		date_of_birth: '01-01-2000',
		email: 'inaamindia@gmail.com',
		emirate: 'GUJARAT',
		gender: 'M',
		is_profile_complete: true,
		name: 'Inaam India Prodd',
		nationality: 'India',
		status: 200,
		username: '918888888888',
		wallet: {
			barcode: {
				url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/3f4c965c-4a76-5edc-9519-e0cb895b9a85',
				url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/9100005571.png',
				uuid: 'd5dd43d9-a2d9-4701-9add-44d6e25723f7',
			},
			card_number: '9100005571',
			lifetime_points: 0,
			points: 40900,
		},
	},
	updateUserProfile: { status: 200 },
	customerLogout: { status: 200 },
	deleteAccount: { status: 200 },

	// Store API
	fetchStores: {
		status: 200,
		store_list: [
			{
				uuid: '8eac067f-4916-412e-9a99-e6ea295e6958',
				date_created: null,
				date_modified: '03 Oct, 2022',
				name: 'NESTO Hypermarket',
				location: {
					latitude: '11.2585739',
					longitude: '75.7930716',
					region: 'Kerala',
					address: 'Gokulam Galleria Mall Ground floor, Arayidathupalam, Calicut- 9746400222',
					city: 'Calicut',
					country: 'India',
				},
				company_code: '8811',
				sap_code: 'GKLM',
				order_index: 1,
				is_enabled: true,
				is_archived: false,
				image: {
					uuid: 'a4390735-6076-4b98-9fa0-ae1baecef451',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/Nesto-Gokulam.jpeg',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/2253d458-74c3-5622-81f9-37350be1fe9f',
				},
				cohort: {
					uuid: '6441db9f-5abb-4105-86d0-6077b4620cf9',
					date_created: '03 Mar, 2022',
					date_modified: '14 Jul, 2022',
					name: 'NESTO Hypermarket - GKLM - 8811',
					cohort_type: 'ST',
					is_archived: false,
					is_protected: false,
					store_sap_code: 'GKLM',
					store_company_code: '8811',
				},
				offers: 0,
			},
			{
				uuid: 'f6f1f69c-e122-4a62-9fec-80f0cb8f67c3',
				date_created: null,
				date_modified: '03 Oct, 2022',
				name: 'NESTO Hypermarket',
				location: {
					latitude: '11.2482909',
					longitude: '75.8332565',
					region: 'Kerala',
					address: 'HiLITE Mall, -1 Level, NH Thondayad Bypass, Calicut- 9605442442',
					city: 'Calicut',
					country: 'India',
				},
				company_code: '8810',
				sap_code: 'HLTM',
				order_index: 3,
				is_enabled: true,
				is_archived: false,
				image: {
					uuid: '05fc7f1c-1dfb-499a-a7ea-3c2868fc33ac',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/Nesto_HiLite_1.jpeg',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/10c7f0dc-9b6f-5b41-bc62-79d871d3b988',
				},
				cohort: {
					uuid: 'a9f087f9-a1a4-4d86-84df-4f49cb4ba2c3',
					date_created: '03 Mar, 2022',
					date_modified: '03 Oct, 2022',
					name: 'NESTO Hypermarket - HLTM - 8810',
					cohort_type: 'ST',
					is_archived: false,
					is_protected: false,
					store_sap_code: 'HLTM',
					store_company_code: '8810',
				},
				offers: 0,
			},
			{
				uuid: '51142302-8a4d-46b4-b815-c85bbb005022',
				date_created: '09 Mar, 2022',
				date_modified: '03 Oct, 2022',
				name: 'NESTO Hypermarket',
				location: {
					latitude: '11.62404',
					longitude: '76.08391',
					region: 'Kerala',
					address: 'Kalpetta Main Road, Green Land Nagar, Wayanad- 8137054333',
					city: 'Wayanad',
					country: 'India',
				},
				company_code: '8813',
				sap_code: 'KLPT',
				order_index: 2,
				is_enabled: true,
				is_archived: false,
				image: {
					uuid: 'fb511530-af1e-4280-a040-c0d9e90db8e5',
					url_original:
						'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/Kalpetta-Cover-Image_hMk72PJ.jpeg',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/2eb84c94-8f75-5b3a-907c-cb97a83a34ae',
				},
				cohort: {
					uuid: '00a14e48-1ea8-4645-b0c3-f83f29be9d1a',
					date_created: '09 Mar, 2022',
					date_modified: '14 Jul, 2022',
					name: 'NESTO Hypermarket - KLPT - 8813',
					cohort_type: 'ST',
					is_archived: false,
					is_protected: false,
					store_sap_code: 'KLPT',
					store_company_code: '8813',
				},
				offers: 0,
			},
		],
	},
	setSelectedStore: { status: 200 },

	// Transactions API
	fetchTransactionHistory: {
		status: 200,
		transaction_list: [
			{
				timestamp: '26 Jun, 2022',
				points: -100,
				type: 'Redemption',
				store: '',
				receipt: '848196495011-9100005571',
			},
			{
				timestamp: '28 Apr, 2022',
				points: -200,
				type: 'Redemption',
				store: '',
				receipt: '811215611915-9100005571',
			},
			{
				timestamp: '28 Apr, 2022',
				points: -500,
				type: 'Redemption',
				store: '',
				receipt: '774732692322-9100005571',
			},
			{
				timestamp: '21 Mar, 2022',
				points: 50000,
				type: 'Sales',
				store: 'INAAM',
				receipt: 'INAAM0868910562-9100005571',
			},
		],
	},
	syncTransactionHistory: {},

	// Vouchers API
	fetchVouchers: {
		status: 200,
		voucher_wallet_list: [
			{
				uuid: 'dad88a81-33a6-488d-ba70-6b0189b5bb19',
				date_created: '07 Oct, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '002180683421',
				cost: 1400,
				amount: 700,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: 'bf1403cb-238e-4574-83ea-0383a1c3c090',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/002180683421.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/cc869c2c-feb1-5285-9f72-46a68e8d0214',
				},
				status: 'generated',
				timestamp_created: 1665120743.90239,
			},
			{
				uuid: 'e1ff280c-9330-43d6-9845-b4deefe7ebb4',
				date_created: '26 Sep, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '530176076572',
				cost: 300,
				amount: 150,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: '427a350d-6fa6-4e1a-9bd9-0d4896725fd0',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/530176076572_qXTaDux.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/99ac791d-9648-5468-a197-76338b22642c_p1zvWSx',
				},
				status: 'generated',
				timestamp_created: 1664175743.801355,
			},
			{
				uuid: '824ab8a2-8052-4d6a-979e-892b713be03b',
				date_created: '30 Sep, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '189338083679',
				cost: 200,
				amount: 100,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: 'ff396b53-e01a-4d66-8661-8fbcfaed107b',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/189338083679_XUxh4qm.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/d6236983-a474-5e00-930e-6f46dc98cf8e_jFmhURf',
				},
				status: 'generated',
				timestamp_created: 1664520634.354023,
			},
			{
				uuid: 'ff40d9fc-e72d-4b6c-b147-6950d967f433',
				date_created: '26 Jun, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '848196495011',
				cost: 100,
				amount: 50,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: '2dbdd321-6857-46ce-bbce-afd4a8fff022',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/848196495011.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/85335abe-2e64-595d-8a7e-c6c659f91b89',
				},
				status: 'generated',
				timestamp_created: 1656183716.841517,
			},
			{
				uuid: 'eaa28afb-cb1d-4f00-9c64-2fd02936e6e7',
				date_created: '28 Apr, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '811215611915',
				cost: 200,
				amount: 100,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: '7b472f13-d7ec-4d8c-8da8-d36110571df0',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/811215611915.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/86b3ba41-fedf-51ae-bd4e-1beaead877b3',
				},
				status: 'generated',
				timestamp_created: 1651144376.148065,
			},
			{
				uuid: '1a264757-92ab-480a-afbd-004cc85a918a',
				date_created: '28 Apr, 2022',
				date_modified: '10 Oct, 2022',
				voucher_code: '774732692322',
				cost: 500,
				amount: 250,
				is_used: false,
				date_redemption: null,
				user: {
					gender: 'M',
					email: 'inaamindia@gmail.com',
					emirate: 'GUJARAT',
					date_of_birth: '01-01-2000',
					username: '918888888888',
					contact_number: '8888888888',
					country_code: '91',
					nationality: 'India',
					name: 'Inaam India Prod',
					card_number: '9100005571',
					date_created: '02-25-2022',
				},
				barcode: {
					uuid: '9c3f33aa-0c88-4006-a7e8-1d7d4fa8f1bb',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/774732692322.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/a039ee2b-c136-5727-96a5-7464280fae13',
				},
				status: 'generated',
				timestamp_created: 1651109425.809614,
			},
		],
	},
	generateVoucher: {
		status: 200,
		voucher_details: {
			uuid: 'd711d939-ac44-4373-b38d-82843343a1f0',
			date_created: '10 Oct, 2022',
			date_modified: '10 Oct, 2022',
			voucher_code: '707099029973',
			cost: 1000,
			amount: 500,
			is_used: false,
			date_redemption: null,
			user: {
				gender: 'M',
				email: 'inaamindia@gmail.com',
				emirate: 'GUJARAT',
				date_of_birth: '01-01-2000',
				username: '918888888888',
				contact_number: '8888888888',
				country_code: '91',
				nationality: 'India',
				name: 'Inaam India Prod',
				card_number: '9100005571',
				date_created: '02-25-2022',
			},
			barcode: {
				uuid: '2851d1e7-cfd3-4d50-b1f2-3232107053ed',
				url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/707099029973.png',
				url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/57bb1a05-9314-5e16-886a-a4b7f2f0c0ca',
			},
			status: 'generated',
			timestamp_created: 1665397416.312446,
		},
		total_vouchers: 7,
		message: 'Voucher generated successfully!',
	},
	requestVoucherGeneration: {
		status: 200,
		uuid: 'cd86530b-680a-4d02-904d-2da08cde7699',
		date_created: '10 Oct, 2022',
		date_modified: '10 Oct, 2022',
		otp: '111111',
		points: 1000,
		last_otp_sent_time: '2022-10-10T15:52:15.128521+05:30',
		otp_verified_time: null,
		user: {
			gender: 'M',
			email: 'inaamindia@gmail.com',
			emirate: 'GUJARAT',
			date_of_birth: '01-01-2000',
			username: '918888888888',
			contact_number: '8888888888',
			country_code: '91',
			nationality: 'India',
			name: 'Inaam India Prod',
			card_number: '9100005571',
			date_created: '02-25-2022',
		},
	},
	verifyVoucherGeneration: {
		status: 200,
		voucher_details: {
			uuid: 'd711d939-ac44-4373-b38d-82843343a1f0',
			date_created: '10 Oct, 2022',
			date_modified: '10 Oct, 2022',
			voucher_code: '707099029973',
			cost: 1000,
			amount: 500,
			is_used: false,
			date_redemption: null,
			user: {
				gender: 'M',
				email: 'inaamindia@gmail.com',
				emirate: 'GUJARAT',
				date_of_birth: '01-01-2000',
				username: '918888888888',
				contact_number: '8888888888',
				country_code: '91',
				nationality: 'India',
				name: 'Inaam India Prod',
				card_number: '9100005571',
				date_created: '02-25-2022',
			},
			barcode: {
				uuid: '2851d1e7-cfd3-4d50-b1f2-3232107053ed',
				url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/707099029973.png',
				url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/57bb1a05-9314-5e16-886a-a4b7f2f0c0ca',
			},
			status: 'generated',
			timestamp_created: 1665397416.312446,
		},
		total_vouchers: 7,
		message: 'Voucher generated successfully!',
	},
	syncVouchers: { status: 200 },

	// WhatsNew API
	fetchWhatsNew: {
		id: 3,
		uuid: '2dd29f3e-3685-4caa-bcec-9514cd03f3ba',
		date_created: 1647316521.03036,
		date_modified: 1647316730.38542,
		version: '15.0.0',
		description: 'version 15 updated',
		status: 200,
	},

	// Feedback API
	fetchFeedback: {},
	submitFeedback: {},
	checkCustomerSurveyStatus: {},
	submitRecommendation: {},

	// Flyer API
	fetchSections: {
		status: 200,
		section_list: [
			{
				uuid: 'e2322cef-1df8-4399-863f-925c66989f88',
				date_created: '26 Jun, 2022',
				date_modified: '10 Oct, 2022',
				name: 'Smart Deals',
				is_published: true,
				order_index: 3,
				type: {
					name: 'BannerAd',
					limit: 1,
				},
				flyer_list: [],
				promotion_list: [],
			},
			{
				uuid: '5bc1e73f-382c-4461-826e-ae2809c1e6cd',
				date_created: '26 Jun, 2022',
				date_modified: '10 Oct, 2022',
				name: 'Nesto is now 0 km away!',
				is_published: true,
				order_index: 4,
				type: {
					name: 'BannerAd',
					limit: 1,
				},
				flyer_list: [],
				promotion_list: [
					{
						uuid: '0182bdd3-5352-4b86-8c93-dde209b0b791',
						date_created: '26 Jun, 2022',
						date_modified: '10 Oct, 2022',
						title: 'Nesto is now 0 km away!',
						description:
							'<p>Nesto Online Shopping makes your shopping worthy and happier. Browse the Midweek, Weekend, Sunday and Special offers at your favorite store online now.</p><p><br></p><p>Nesto brings a premium online shopping experience to our customers through a new and better online platform managed exclusively by Nesto Group.</p>',
						cost: 0,
						amount: 0,
						type: 'information',
						item_code: '0',
						uom: '0',
						trigger_amount: 0,
						order_index: 1,
						start_time: '2022-09-23T00:00:00+05:30',
						end_time: '2022-10-31T10:00:00+05:30',
						is_published: true,
						is_deleted: false,
						section: {
							uuid: '5bc1e73f-382c-4461-826e-ae2809c1e6cd',
							date_created: '26 Jun, 2022',
							date_modified: '10 Oct, 2022',
							name: 'Nesto is now 0 km away!',
							is_published: true,
							order_index: 4,
							type: {
								name: 'BannerAd',
								limit: 1,
							},
						},
						outer_image: {
							uuid: 'ae810593-abbb-4034-a4db-abecedf483da',
							url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/f2_3WTnTKS.png',
							url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/e49556bb-9965-50fd-b1f7-a933ada014bd_jTxt9SR',
						},
						inner_image: {
							uuid: 'eb029bc0-d03a-420f-bfde-f85e8dd8da95',
							url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/f2_yZDPhB5.png',
							url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/e49556bb-9965-50fd-b1f7-a933ada014bd_ej8gCke',
						},
						cohort_list: [],
						generated: false,
					},
				],
			},
		],
	},
	fetchFlyers: {
		status: 200,
		flyer_list: [
			{
				uuid: '183186f8-526e-4607-b74c-93711cc5c359',
				date_created: '10 Oct, 2022',
				date_modified: '10 Oct, 2022',
				title: 'New Flyer',
				description: 'This is a flyer',
				order_index: 1,
				start_time: '2022-09-15T00:00:00+05:30',
				end_time: '2022-10-19T23:59:59+05:30',
				is_published: true,
				section: {
					uuid: '85614ad9-d01c-4b78-a3ee-bdf87509bdb1',
					date_created: '04 Oct, 2022',
					date_modified: '10 Oct, 2022',
					name: 'Section 3',
					is_published: true,
					order_index: 1,
					type: {
						name: 'Grid',
						limit: 15,
					},
				},
				outer_image: {
					uuid: '08acba38-0e09-484b-8cdc-3561841f4155',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/f1_B0q4pbv_ZzEqoj8.png',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/55346590-5d6e-56a7-a5bc-2858d5d45185_vtgYovF',
				},
				inner_images: [
					{
						uuid: 'e02a27b9-4e3d-4316-b35c-a5fead0e4efd',
						url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/flyer1_yooICpo.png',
						url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/6d5eaabc-3c76-5fa3-988d-57b9d88af711_3YolvBy',
					},
				],
				stores: [
					{
						uuid: '8eac067f-4916-412e-9a99-e6ea295e6958',
						date_created: null,
						date_modified: '03 Oct, 2022',
						name: 'NESTO Hypermarket',
						location: {
							latitude: '11.2585739',
							longitude: '75.7930716',
							region: 'Kerala',
							address: 'Gokulam Galleria Mall Ground floor, Arayidathupalam, Calicut- 9746400222',
							city: 'Calicut',
							country: 'India',
						},
						company_code: '8811',
						sap_code: 'GKLM',
						order_index: 1,
						is_enabled: true,
						is_archived: false,
						image: {
							uuid: 'a4390735-6076-4b98-9fa0-ae1baecef451',
							url_original:
								'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/Nesto-Gokulam.jpeg',
							url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/2253d458-74c3-5622-81f9-37350be1fe9f',
						},
						cohort: {
							uuid: '6441db9f-5abb-4105-86d0-6077b4620cf9',
							date_created: '03 Mar, 2022',
							date_modified: '14 Jul, 2022',
							name: 'NESTO Hypermarket - GKLM - 8811',
							cohort_type: 'ST',
							is_archived: false,
							is_protected: false,
							store_sap_code: 'GKLM',
							store_company_code: '8811',
						},
					},
				],
			},
		],
	},
	fetchFlyerDetails: {
		status: 200,
		uuid: '183186f8-526e-4607-b74c-93711cc5c359',
		date_created: '10 Oct, 2022',
		date_modified: '10 Oct, 2022',
		title: 'New Flyer',
		description: 'This is a flyer',
		order_index: 1,
		start_time: '2022-09-15T00:00:00+05:30',
		end_time: '2022-10-19T23:59:59+05:30',
		is_published: false,
		section: {
			uuid: '85614ad9-d01c-4b78-a3ee-bdf87509bdb1',
			date_created: '04 Oct, 2022',
			date_modified: '06 Oct, 2022',
			name: 'Section 3',
			is_published: false,
			order_index: 1,
			type: {
				name: 'Grid',
				limit: 15,
			},
		},
		outer_image: {
			uuid: '08acba38-0e09-484b-8cdc-3561841f4155',
			url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/f1_B0q4pbv_ZzEqoj8.png',
			url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/55346590-5d6e-56a7-a5bc-2858d5d45185_vtgYovF',
		},
		inner_images: [
			{
				uuid: 'e02a27b9-4e3d-4316-b35c-a5fead0e4efd',
				url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/flyer1_yooICpo.png',
				url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/6d5eaabc-3c76-5fa3-988d-57b9d88af711_3YolvBy',
			},
		],
		stores: [
			{
				uuid: '8eac067f-4916-412e-9a99-e6ea295e6958',
				date_created: null,
				date_modified: '03 Oct, 2022',
				name: 'NESTO Hypermarket',
				location: {
					latitude: '11.2585739',
					longitude: '75.7930716',
					region: 'Kerala',
					address: 'Gokulam Galleria Mall Ground floor, Arayidathupalam, Calicut- 9746400222',
					city: 'Calicut',
					country: 'India',
				},
				company_code: '8811',
				sap_code: 'GKLM',
				order_index: 1,
				is_enabled: true,
				is_archived: false,
				image: {
					uuid: 'a4390735-6076-4b98-9fa0-ae1baecef451',
					url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/Nesto-Gokulam.jpeg',
					url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/2253d458-74c3-5622-81f9-37350be1fe9f',
				},
				cohort: {
					uuid: '6441db9f-5abb-4105-86d0-6077b4620cf9',
					date_created: '03 Mar, 2022',
					date_modified: '14 Jul, 2022',
					name: 'NESTO Hypermarket - GKLM - 8811',
					cohort_type: 'ST',
					is_archived: false,
					is_protected: false,
					store_sap_code: 'GKLM',
					store_company_code: '8811',
				},
			},
		],
	},

	// Promotion API
	fetchPromotionDetails: {
		status: 200,
		uuid: 'ad1d42c9-f0a7-44c4-8a82-a4e0e87a9561',
		date_created: '11 Oct, 2022',
		date_modified: '11 Oct, 2022',
		title: 'Promotion Testing',
		description: '<p>Boom Boom 2.0</p>',
		cost: 5000,
		amount: 250,
		type: 'Transaction',
		item_code: '3',
		uom: '4',
		trigger_amount: 250,
		order_index: 1,
		start_time: '2022-10-01T00:00:00+05:30',
		end_time: '2022-12-29T23:59:59+05:30',
		is_published: true,
		is_deleted: false,
		section: {
			uuid: '85614ad9-d01c-4b78-a3ee-bdf87509bdb1',
			date_created: '04 Oct, 2022',
			date_modified: '11 Oct, 2022',
			name: 'Section 3',
			is_published: true,
			order_index: 1,
			type: {
				name: 'Grid',
				limit: 15,
			},
		},
		outer_image: {
			uuid: '646d0907-1f86-4a8b-b47f-8120dc425086',
			url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/promo2-outer_Uq8ggJJ.png',
			url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/b6f2a494-a521-5933-83f5-fbbff404885c_4oJ9N8R',
		},
		inner_image: {
			uuid: 'b45887be-51aa-4f65-aaf5-517d8f500308',
			url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/promo2-inner_8dFA5DI.png',
			url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/79b75526-9bb5-55c1-9123-38f033886717_L3tZqxb',
		},
		cohort_list: [],
		generated: false,
	},
	claimPromotion: {
		status: 200,
		uuid: '6b419142-f891-4672-b7e9-7751c04d4117',
		barcode: {
			uuid: 'ea19978e-ebc3-4cd4-a91b-cf34a2262e0e',
			url_original: 'https://wig-wams-s3-bucket.s3.amazonaws.com/original_image/028552477604.png',
			url: 'https://wig-wams-s3-bucket.s3.amazonaws.com/optimized_image/d3599ee6-9724-5348-8cfa-b24088c25af3',
		},
		date_created: '11 Oct, 2022',
		date_modified: '11 Oct, 2022',
		message: 'success',
	},

	// Other API
	submitUserQuery: { status: 200 },
	fetchAppVersion: { status: 200, version: '9.4.0' },
};

export default {
	registerPlatformDevice: (...params) => ({ data: staticResponses.registerPlatformDevice }),
	registerUsertoDevice: (...params) => ({ data: staticResponses.registerUsertoDevice }),
	fetchCountryConfiguration: (...params) => ({ data: staticResponses.fetchCountryConfiguration }),
	sendLoginOTP: (...params) => ({ data: staticResponses.sendLoginOTP }),
	customerLogin: (...params) => ({ data: staticResponses.customerLogin }),
	fetchUserProfile: (...params) => ({ data: staticResponses.fetchUserProfile }),
	updateUserProfile: (...params) => ({ data: staticResponses.updateUserProfile }),
	customerLogout: (...params) => ({ data: staticResponses.customerLogout }),
	deleteAccount: (...params) => ({ data: staticResponses.deleteAccount }),
	fetchStores: (...params) => ({ data: staticResponses.fetchStores }),
	setSelectedStore: (...params) => ({ data: staticResponses.setSelectedStore }),
	fetchTransactionHistory: (...params) => ({ data: staticResponses.fetchTransactionHistory }),
	syncTransactionHistory: (...params) => ({ data: staticResponses.syncTransactionHistory }),
	fetchVouchers: (...params) => ({ data: staticResponses.fetchVouchers }),
	generateVoucher: (...params) => ({ data: staticResponses.generateVoucher }),
	requestVoucherGeneration: (...params) => ({ data: staticResponses.requestVoucherGeneration }),
	verifyVoucherGeneration: (...params) => ({ data: staticResponses.verifyVoucherGeneration }),
	syncVouchers: (...params) => ({ data: staticResponses.syncVouchers }),
	fetchWhatsNew: (...params) => ({ data: staticResponses.fetchWhatsNew }),
	fetchFeedback: (...params) => ({ data: staticResponses.fetchFeedback }),
	submitFeedback: (...params) => ({ data: staticResponses.submitFeedback }),
	checkCustomerSurveyStatus: (...params) => ({ data: staticResponses.checkCustomerSurveyStatus }),
	submitRecommendation: (...params) => ({ data: staticResponses.submitRecommendation }),
	fetchSections: (...params) => ({ data: staticResponses.fetchSections }),
	fetchFlyers: (...params) => ({ data: staticResponses.fetchFlyers }),
	fetchFlyerDetails: (...params) => ({ data: staticResponses.fetchFlyerDetails }),
	fetchPromotionDetails: (...params) => ({ data: staticResponses.fetchPromotionDetails }),
	claimPromotion: (...params) => ({ data: staticResponses.claimPromotion }),
	submitUserQuery: (...params) => ({ data: staticResponses.submitUserQuery }),
	fetchAppVersion: (...params) => ({ data: staticResponses.fetchAppVersion }),
};
